### PR TITLE
Issue #61: support DataDog JSON as of 2021-07-19.

### PR DESCRIPTION
**Pull request by fgm**
- Includes extra lines spacing for better results after terraform fmt.
- Removes multiple erroneous duplicate keys in objects and orders keys to prevent it from happening again.

# Why?

DataDog is constantly adding new fields, and changed some schema with version 3 of its provider, causing issue #61 .

# How?

- Mostly adding entries for the new properties
- Adding a couple of functions to support block transformations for new elements and to support line spacing contorl

# UI Changes

- Added a CLI version: 
  - build with `npm build`
  - run with `yarn convert < somefile.json > somefile.tf` or `yarn convert somefile.json`

## Before

No CLI.

## After

A CLI.

### CODE REVIEW

**Comment by alectronic0** [comment]
Ran the CLI version seem to work out for me 👍

**Comment by nwithers-ecr** [comment]
I can't seem to be able to run this. 
```
❯ yarn build

yarn run v1.22.15
$ rm -f lib/*; babel app -d lib
app/cli.js -> lib/cli.js
app/dashboard-converter.js -> lib/dashboard-converter.js
app/monitor-converter.js -> lib/monitor-converter.js
app/popup.js -> lib/popup.js
app/utils.js -> lib/utils.js
Done in 0.48s.

❯ yarn convert postgres-monitor.json

yarn run v1.22.15
$ node lib/cli.js postgres-monitor.json
(node:2032659) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/nwithers/datadog-to-terraform/lib/cli.js:1
import fs from "fs";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

In the package.json I have added "type": "module", as it suggested and still no dice
```
❯ tail package.json
  "lint-staged": {
    "**/*": "yarn prettier --write --ignore-unknown"
  },
  "scripts": {
    "type": "module",
    "build": "rm -f lib/*; babel app -d lib",
    "convert": "node lib/cli.js",
    "test": "jest"
  }
}
```

**Comment by nwithers-ecr** [comment]
node version: v10.19.0
deleting the package-lock.json and adding those missing json keys enabled me to run the command successfully.

**Comment by danielMensah** [comment]
any plans to release this?

**Review by danielMensah — APPROVED** [review]

**Comment by fgm** [comment]
@danielMensah after two years, I just converted that PR to a complete new implementation in Go, at https://github.com/fgm/jastify , that drops the browser extension and only contains the CLI.

**Pull request closed without merging**
