### PR TITLE
Ignore deprecated monitor properties

### LINKED ISSUE #57: Errors converting Monitor
❗️Can't convert key 'queryConfig'
❗️Can't convert key 'aggregation'

```
{
	"id": 32168291,
	"name": "DueDiligence - KYC - [Non-Prod] - Errors on Logs",
	"type": "log alert",
	"query": "logs(\"source:due_diligence env:(dev OR qa OR sbox) appgroup:dd-kyc status:(error OR emergency)\").index(\"*\").rollup(\"count\").by(\"service\").last(\"15m\") >= 1",
	"message": "{{#is_alert}}:notify @slack-DueDiligence-dd-dev-logs{{/is_alert}}",
	"tags": [
		"appgroup:dd-kyc",
		"duediligence",
		"log-alert",
		"monitor_env:non-prod",
		"terraform"
	],
	"options": {
		"include_tags": true,
		"notify_audit": false,
		"locked": true,
		"timeout_h": 0,
		"silenced": {},
		"enable_logs_sample": true,
		"thresholds": {
			"critical": 1
		},
		"new_host_delay": 300,
		"require_full_window": true,
		"notify_no_data": false,
		"renotify_interval": 0,
		"groupby_simple_monitor": true,
		"queryConfig": {
			"logset": {
				"name": "*"
			},
			"track": "logs",
			"timeRange": {
				"to": 1616759698501,
				"live": true,
				"from": 1616745298501
			},
			"queryString": "source:due_diligence AND env:(dev OR qa OR sbox) AND appgroup:dd-kyc AND status:(error OR emergency)",
			"indexes": [
				"*"
			],
			"queryIsFailed": false
		},
		"aggregation": {
			"metric": "count",
			"type": "count",
			"groupBy": "core_service"
		}
	},
	"priority": 4
}
```

### PR DESCRIPTION
**Pull request by flavio-cadete-cko**
Ignore aggregation & queryConfig
Fix #57

### CODE REVIEW

**Comment by flavio-cadete-cko** [comment]
@laurmurclar is possible to merge both PRs?

**Comment by laurmurclar** [comment]
Hey @flavio-cadete-cko, sorry for the delay! I took a break from code for a while. I'll take a proper look at this this evening and get a release out if possible 👍

**Comment by cnguyen383** [comment]
hey @laurmurclar, I ran into this same issue while trying to convert log monitor into TF. Can this be merged in and cut a release?

**Comment by laurmurclar** [comment]
Hey folks, I'm sorry but I've made the decision not to support log monitors right now. They don't seem to be used by many other people, they're quite a bit more complicated than other monitor types and they're not something I can test/explore with my current Datadog setup. Each PR (for any monitor or dashboard change) already requires a lot of testing and doc-checking to make sure everything works right. The extra overhead for log monitors isn't worth it at this time, but of course we can revisit that decision in future if there's an uptake in demand.

You can of course use the fork you've made by following the local setup instructions in the [contributing guide](https://github.com/laurmurclar/datadog-to-terraform/blob/v3.6.0/CONTRIBUTING.md#development-setup), so your work isn't wasted. Thank you for your time anyway, I appreciate the work you've put in

**Pull request closed without merging**
